apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace alvo para a implantação
namespace: geonode-system

# Inclui os arquivos manifestos estáticos
resources:
  - scc-geonode.yaml

# Gera um ConfigMap no cluster com o conteúdo do arquivo de propriedades JDBC
configMapGenerator:
  - name: geoserver-jdbc-configmap
    files:
      - jdbcconfig.properties=geoserver-jdbc-config.properties

generatorOptions:
  # Desabilita o sufixo numérico no nome do ConfigMap para que o Helm saiba o nome exato para montar
  disableNameSuffixHash: true
